#!/bin/bash

ANSIBLE_BUILTIN_MODULE_LIST=()
ANSIBLE_BUILTIN_MODULE_LIST+=("add_host")
ANSIBLE_BUILTIN_MODULE_LIST+=("apt")
ANSIBLE_BUILTIN_MODULE_LIST+=("apt_key")
ANSIBLE_BUILTIN_MODULE_LIST+=("apt_repository")
ANSIBLE_BUILTIN_MODULE_LIST+=("assemble")
ANSIBLE_BUILTIN_MODULE_LIST+=("assert")
ANSIBLE_BUILTIN_MODULE_LIST+=("async_status")
ANSIBLE_BUILTIN_MODULE_LIST+=("async_wrapper")
ANSIBLE_BUILTIN_MODULE_LIST+=("blockinfile")
ANSIBLE_BUILTIN_MODULE_LIST+=("command")
ANSIBLE_BUILTIN_MODULE_LIST+=("copy")
ANSIBLE_BUILTIN_MODULE_LIST+=("cron")
ANSIBLE_BUILTIN_MODULE_LIST+=("debconf")
ANSIBLE_BUILTIN_MODULE_LIST+=("debug")
ANSIBLE_BUILTIN_MODULE_LIST+=("dnf")
ANSIBLE_BUILTIN_MODULE_LIST+=("dpkg_selections")
ANSIBLE_BUILTIN_MODULE_LIST+=("expect")
ANSIBLE_BUILTIN_MODULE_LIST+=("fail")
ANSIBLE_BUILTIN_MODULE_LIST+=("fetch")
ANSIBLE_BUILTIN_MODULE_LIST+=("file")
ANSIBLE_BUILTIN_MODULE_LIST+=("find")
ANSIBLE_BUILTIN_MODULE_LIST+=("gather_facts")
ANSIBLE_BUILTIN_MODULE_LIST+=("get_url")
ANSIBLE_BUILTIN_MODULE_LIST+=("getent")
ANSIBLE_BUILTIN_MODULE_LIST+=("git")
ANSIBLE_BUILTIN_MODULE_LIST+=("group")
ANSIBLE_BUILTIN_MODULE_LIST+=("group_by")
ANSIBLE_BUILTIN_MODULE_LIST+=("hostname")
ANSIBLE_BUILTIN_MODULE_LIST+=("import_playbook")
ANSIBLE_BUILTIN_MODULE_LIST+=("import_role")
ANSIBLE_BUILTIN_MODULE_LIST+=("import_tasks")
ANSIBLE_BUILTIN_MODULE_LIST+=("include_role")
ANSIBLE_BUILTIN_MODULE_LIST+=("include_tasks")
ANSIBLE_BUILTIN_MODULE_LIST+=("include_vars")
ANSIBLE_BUILTIN_MODULE_LIST+=("iptables")
ANSIBLE_BUILTIN_MODULE_LIST+=("known_hosts")
ANSIBLE_BUILTIN_MODULE_LIST+=("lineinfile")
ANSIBLE_BUILTIN_MODULE_LIST+=("meta")
ANSIBLE_BUILTIN_MODULE_LIST+=("package")
ANSIBLE_BUILTIN_MODULE_LIST+=("package_facts")
ANSIBLE_BUILTIN_MODULE_LIST+=("pause")
ANSIBLE_BUILTIN_MODULE_LIST+=("ping")
ANSIBLE_BUILTIN_MODULE_LIST+=("pip")
ANSIBLE_BUILTIN_MODULE_LIST+=("raw")
ANSIBLE_BUILTIN_MODULE_LIST+=("reboot")
ANSIBLE_BUILTIN_MODULE_LIST+=("replace")
ANSIBLE_BUILTIN_MODULE_LIST+=("rpm_key")
ANSIBLE_BUILTIN_MODULE_LIST+=("script")
ANSIBLE_BUILTIN_MODULE_LIST+=("service")
ANSIBLE_BUILTIN_MODULE_LIST+=("service_facts")
ANSIBLE_BUILTIN_MODULE_LIST+=("set_fact")
ANSIBLE_BUILTIN_MODULE_LIST+=("set_stats")
ANSIBLE_BUILTIN_MODULE_LIST+=("setup")
ANSIBLE_BUILTIN_MODULE_LIST+=("shell")
ANSIBLE_BUILTIN_MODULE_LIST+=("slurp")
ANSIBLE_BUILTIN_MODULE_LIST+=("stat")
ANSIBLE_BUILTIN_MODULE_LIST+=("subversion")
ANSIBLE_BUILTIN_MODULE_LIST+=("systemd")
ANSIBLE_BUILTIN_MODULE_LIST+=("systemd_service")
ANSIBLE_BUILTIN_MODULE_LIST+=("sysvinit")
ANSIBLE_BUILTIN_MODULE_LIST+=("tempfile")
ANSIBLE_BUILTIN_MODULE_LIST+=("template")
ANSIBLE_BUILTIN_MODULE_LIST+=("unarchive")
ANSIBLE_BUILTIN_MODULE_LIST+=("uri")
ANSIBLE_BUILTIN_MODULE_LIST+=("user")
ANSIBLE_BUILTIN_MODULE_LIST+=("validate_argument_spec")
ANSIBLE_BUILTIN_MODULE_LIST+=("wait_for")
ANSIBLE_BUILTIN_MODULE_LIST+=("wait_for_connection")
ANSIBLE_BUILTIN_MODULE_LIST+=("yum")
ANSIBLE_BUILTIN_MODULE_LIST+=("yum_repository")

local DELIM='|'
printf -v ANSIBLE_BUILTIN_MODULES_REGEX "%s${DELIM}" "${ANSIBLE_BUILTIN_MODULE_LIST[@]}"
ANSIBLE_BUILTIN_MODULES_REGEX=${ANSIBLE_BUILTIN_MODULES_REGEX%$DELIM}

echo "ANSIBLE_BUILTIN_MODULES_REGEX=${ANSIBLE_BUILTIN_MODULES_REGEX}"

#ANSIBLE_BUILTIN_MODULES_REGEX1_HARDCODED=" (add_host|apt|apt_key|apt_repository|assemble|assert|async_status|async_wrapper|blockinfile|command|copy|cron|debconf|debug|dnf|dpkg_selections|expect|fail|fetch|file|find|gather_facts|get_url|getent|git|group|group_by|hostname|import_playbook|import_role|import_tasks|include_role|include_tasks|include_vars|iptables|known_hosts|lineinfile|meta|package|package_facts|pause|ping|pip|raw|reboot|replace|rpm_key|script|service|service_facts|set_fact|set_stats|setup|shell|slurp|stat|subversion|systemd|systemd_service|sysvinit|tempfile|template|unarchive|uri|user|validate_argument_spec|wait_for|wait_for_connection|yum|yum_repository)\:\s*$"
#ANSIBLE_BUILTIN_MODULES_REGEX1_HARDCODED=" (command|import_playbook|import_role|import_tasks|include_role|include_tasks|include_vars|meta|shell):"
# to ansible.builtin.$1:


ANSIBLE_POSIX_MODULE_LIST=()
ANSIBLE_POSIX_MODULE_LIST+=("acl")
ANSIBLE_POSIX_MODULE_LIST+=("at")
ANSIBLE_POSIX_MODULE_LIST+=("authorized_key")
ANSIBLE_POSIX_MODULE_LIST+=("firewalld")
ANSIBLE_POSIX_MODULE_LIST+=("firewalld_info")
ANSIBLE_POSIX_MODULE_LIST+=("mount")
ANSIBLE_POSIX_MODULE_LIST+=("patch")
ANSIBLE_POSIX_MODULE_LIST+=("rhel_facts")
ANSIBLE_POSIX_MODULE_LIST+=("rhel_rpm_ostree")
ANSIBLE_POSIX_MODULE_LIST+=("rpm_ostree_upgrade")
ANSIBLE_POSIX_MODULE_LIST+=("seboolean")
ANSIBLE_POSIX_MODULE_LIST+=("selinux")
ANSIBLE_POSIX_MODULE_LIST+=("synchronize")
ANSIBLE_POSIX_MODULE_LIST+=("sysctl")

local DELIM='|'
printf -v ANSIBLE_POSIX_MODULES_REGEX "%s${DELIM}" "${ANSIBLE_POSIX_MODULE_LIST[@]}"
ANSIBLE_POSIX_MODULES_REGEX=${ANSIBLE_POSIX_MODULES_REGEX%$DELIM}

echo "ANSIBLE_POSIX_MODULES_REGEX=${ANSIBLE_POSIX_MODULES_REGEX}"

#ANSIBLE_POSIX_MODULES_REGEX1_HARDCODED=" (acl|at|authorized_key|firewalld|firewalld_info|mount|patch|rhel_facts|rhel_rpm_ostree|rpm_ostree_upgrade|seboolean|selinux|synchronize|sysctl):\s*$"
# to ansible.posix.$1:


ANSIBLE_WINDOWS_MODULE_LIST=()
ANSIBLE_WINDOWS_MODULE_LIST+=("win_acl")
ANSIBLE_WINDOWS_MODULE_LIST+=("win_acl_inheritance")
ANSIBLE_WINDOWS_MODULE_LIST+=("win_certificate_store")
ANSIBLE_WINDOWS_MODULE_LIST+=("win_command")
ANSIBLE_WINDOWS_MODULE_LIST+=("win_copy")
ANSIBLE_WINDOWS_MODULE_LIST+=("win_dns_client")
ANSIBLE_WINDOWS_MODULE_LIST+=("win_domain")
ANSIBLE_WINDOWS_MODULE_LIST+=("win_domain_controller")
ANSIBLE_WINDOWS_MODULE_LIST+=("win_domain_membership")
ANSIBLE_WINDOWS_MODULE_LIST+=("win_dsc")
ANSIBLE_WINDOWS_MODULE_LIST+=("win_environment")
ANSIBLE_WINDOWS_MODULE_LIST+=("win_feature")
ANSIBLE_WINDOWS_MODULE_LIST+=("win_file")
ANSIBLE_WINDOWS_MODULE_LIST+=("win_find")
ANSIBLE_WINDOWS_MODULE_LIST+=("win_get_url")
ANSIBLE_WINDOWS_MODULE_LIST+=("win_group")
ANSIBLE_WINDOWS_MODULE_LIST+=("win_group_membership")
ANSIBLE_WINDOWS_MODULE_LIST+=("win_hostname")
ANSIBLE_WINDOWS_MODULE_LIST+=("win_optional_feature")
ANSIBLE_WINDOWS_MODULE_LIST+=("win_owner")
ANSIBLE_WINDOWS_MODULE_LIST+=("win_package")
ANSIBLE_WINDOWS_MODULE_LIST+=("win_path")
ANSIBLE_WINDOWS_MODULE_LIST+=("win_ping")
ANSIBLE_WINDOWS_MODULE_LIST+=("win_powershell")
ANSIBLE_WINDOWS_MODULE_LIST+=("win_reboot")
ANSIBLE_WINDOWS_MODULE_LIST+=("win_reg_stat")
ANSIBLE_WINDOWS_MODULE_LIST+=("win_regedit")
ANSIBLE_WINDOWS_MODULE_LIST+=("win_service")
ANSIBLE_WINDOWS_MODULE_LIST+=("win_service_info")
ANSIBLE_WINDOWS_MODULE_LIST+=("win_share")
ANSIBLE_WINDOWS_MODULE_LIST+=("win_shell")
ANSIBLE_WINDOWS_MODULE_LIST+=("win_stat")
ANSIBLE_WINDOWS_MODULE_LIST+=("win_tempfile")
ANSIBLE_WINDOWS_MODULE_LIST+=("win_template")
ANSIBLE_WINDOWS_MODULE_LIST+=("win_updates")
ANSIBLE_WINDOWS_MODULE_LIST+=("win_uri")
ANSIBLE_WINDOWS_MODULE_LIST+=("win_user")
ANSIBLE_WINDOWS_MODULE_LIST+=("win_user_right")
ANSIBLE_WINDOWS_MODULE_LIST+=("win_wait_for")
ANSIBLE_WINDOWS_MODULE_LIST+=("win_whoami")

#ANSIBLE_WINDOWS_MODULES_REGEX=" (win_acl|win_acl_inheritance|win_certificate_store|win_command|win_copy|win_dns_client|win_domain|win_domain_controller|win_domain_membership|win_dsc|win_environment|win_feature|win_file|win_find|win_get_url|win_group|win_group_membership|win_hostname|win_optional_feature|win_owner|win_package|win_path|win_ping|win_powershell|win_reboot|win_reg_stat|win_regedit|win_service|win_service_info|win_share|win_shell|win_stat|win_tempfile|win_template|win_updates|win_uri|win_user|win_user_right|win_wait_for|win_whoami):"
# to ansible.windows.$1:


COMMUNITY_GENERAL_MODULE_LIST=()
COMMUNITY_GENERAL_MODULE_LIST+=("psexec")

COMMUNITY_GENERAL_MODULE_LIST+=("alternatives")
COMMUNITY_GENERAL_MODULE_LIST+=("ansible_galaxy_install")
COMMUNITY_GENERAL_MODULE_LIST+=("apache2_mod_proxy")
COMMUNITY_GENERAL_MODULE_LIST+=("apache2_module")
COMMUNITY_GENERAL_MODULE_LIST+=("apk")
COMMUNITY_GENERAL_MODULE_LIST+=("apt_repo")
COMMUNITY_GENERAL_MODULE_LIST+=("apt_rpm")
COMMUNITY_GENERAL_MODULE_LIST+=("archive")
COMMUNITY_GENERAL_MODULE_LIST+=("btrfs_info")
COMMUNITY_GENERAL_MODULE_LIST+=("btrfs_subvolume")
COMMUNITY_GENERAL_MODULE_LIST+=("bundler")
COMMUNITY_GENERAL_MODULE_LIST+=("bzr")
COMMUNITY_GENERAL_MODULE_LIST+=("capabilities")
COMMUNITY_GENERAL_MODULE_LIST+=("cargo")
COMMUNITY_GENERAL_MODULE_LIST+=("cartesian")
COMMUNITY_GENERAL_MODULE_LIST+=("cloud_init_data_facts")
COMMUNITY_GENERAL_MODULE_LIST+=("cloudflare_dns")
COMMUNITY_GENERAL_MODULE_LIST+=("collection_version")
COMMUNITY_GENERAL_MODULE_LIST+=("consul_kv")
COMMUNITY_GENERAL_MODULE_LIST+=("counter")
COMMUNITY_GENERAL_MODULE_LIST+=("cpanm")
COMMUNITY_GENERAL_MODULE_LIST+=("crc32")
COMMUNITY_GENERAL_MODULE_LIST+=("cronvar")
COMMUNITY_GENERAL_MODULE_LIST+=("crypttab")
COMMUNITY_GENERAL_MODULE_LIST+=("cyberarkpassword")
COMMUNITY_GENERAL_MODULE_LIST+=("dependent")
COMMUNITY_GENERAL_MODULE_LIST+=("dict")
COMMUNITY_GENERAL_MODULE_LIST+=("dict_kv")
COMMUNITY_GENERAL_MODULE_LIST+=("dig")
COMMUNITY_GENERAL_MODULE_LIST+=("dnf_config_manager")
COMMUNITY_GENERAL_MODULE_LIST+=("dnf_versionlock")
COMMUNITY_GENERAL_MODULE_LIST+=("dnsimple")
COMMUNITY_GENERAL_MODULE_LIST+=("dnsimple_info")
COMMUNITY_GENERAL_MODULE_LIST+=("dnsmadeeasy")
COMMUNITY_GENERAL_MODULE_LIST+=("dnstxt")
COMMUNITY_GENERAL_MODULE_LIST+=("dpkg_divert")
COMMUNITY_GENERAL_MODULE_LIST+=("dsv")
COMMUNITY_GENERAL_MODULE_LIST+=("easy_install")
COMMUNITY_GENERAL_MODULE_LIST+=("etcd")
COMMUNITY_GENERAL_MODULE_LIST+=("etcd3")
COMMUNITY_GENERAL_MODULE_LIST+=("etcd3")
COMMUNITY_GENERAL_MODULE_LIST+=("facter")
COMMUNITY_GENERAL_MODULE_LIST+=("facter_facts")
COMMUNITY_GENERAL_MODULE_LIST+=("filesize")
COMMUNITY_GENERAL_MODULE_LIST+=("filesystem")
COMMUNITY_GENERAL_MODULE_LIST+=("filetree")
COMMUNITY_GENERAL_MODULE_LIST+=("flattened")
COMMUNITY_GENERAL_MODULE_LIST+=("from_csv")
COMMUNITY_GENERAL_MODULE_LIST+=("from_ini")
COMMUNITY_GENERAL_MODULE_LIST+=("git_config")
COMMUNITY_GENERAL_MODULE_LIST+=("git_config_info")
COMMUNITY_GENERAL_MODULE_LIST+=("groupby_as_dict")
COMMUNITY_GENERAL_MODULE_LIST+=("gunicorn")
COMMUNITY_GENERAL_MODULE_LIST+=("haproxy")
COMMUNITY_GENERAL_MODULE_LIST+=("hashids_decode")
COMMUNITY_GENERAL_MODULE_LIST+=("hashids_encode")
COMMUNITY_GENERAL_MODULE_LIST+=("homebrew")
COMMUNITY_GENERAL_MODULE_LIST+=("homebrew_cask")
COMMUNITY_GENERAL_MODULE_LIST+=("homebrew_tap")
COMMUNITY_GENERAL_MODULE_LIST+=("homectl")
COMMUNITY_GENERAL_MODULE_LIST+=("htpasswd")
COMMUNITY_GENERAL_MODULE_LIST+=("ini_file")
COMMUNITY_GENERAL_MODULE_LIST+=("interfaces_file")
COMMUNITY_GENERAL_MODULE_LIST+=("ip_netns")
COMMUNITY_GENERAL_MODULE_LIST+=("ipbase_info")
COMMUNITY_GENERAL_MODULE_LIST+=("ipify_facts")
COMMUNITY_GENERAL_MODULE_LIST+=("ipinfoio_facts")
COMMUNITY_GENERAL_MODULE_LIST+=("ipmi_boot")
COMMUNITY_GENERAL_MODULE_LIST+=("ipmi_power")
COMMUNITY_GENERAL_MODULE_LIST+=("iptables_state")
COMMUNITY_GENERAL_MODULE_LIST+=("iso_create")
COMMUNITY_GENERAL_MODULE_LIST+=("iso_customize")
COMMUNITY_GENERAL_MODULE_LIST+=("iso_extract")
COMMUNITY_GENERAL_MODULE_LIST+=("java_cert")
COMMUNITY_GENERAL_MODULE_LIST+=("java_keystore")
COMMUNITY_GENERAL_MODULE_LIST+=("jboss")
COMMUNITY_GENERAL_MODULE_LIST+=("jc")
COMMUNITY_GENERAL_MODULE_LIST+=("jenkins_build")
COMMUNITY_GENERAL_MODULE_LIST+=("jenkins_build_info")
COMMUNITY_GENERAL_MODULE_LIST+=("jenkins_job")
COMMUNITY_GENERAL_MODULE_LIST+=("jenkins_job_info")
COMMUNITY_GENERAL_MODULE_LIST+=("jenkins_plugin")
COMMUNITY_GENERAL_MODULE_LIST+=("jenkins_script")
COMMUNITY_GENERAL_MODULE_LIST+=("json_query")
COMMUNITY_GENERAL_MODULE_LIST+=("keep_keys")
COMMUNITY_GENERAL_MODULE_LIST+=("kernel_blacklist")
COMMUNITY_GENERAL_MODULE_LIST+=("keyring")
COMMUNITY_GENERAL_MODULE_LIST+=("keyring")
COMMUNITY_GENERAL_MODULE_LIST+=("keyring_info")
COMMUNITY_GENERAL_MODULE_LIST+=("launchd")
COMMUNITY_GENERAL_MODULE_LIST+=("ldap_attrs")
COMMUNITY_GENERAL_MODULE_LIST+=("ldap_entry")
COMMUNITY_GENERAL_MODULE_LIST+=("ldap_passwd")
COMMUNITY_GENERAL_MODULE_LIST+=("ldap_search")
COMMUNITY_GENERAL_MODULE_LIST+=("listen_ports_facts")
COMMUNITY_GENERAL_MODULE_LIST+=("lists_difference")
COMMUNITY_GENERAL_MODULE_LIST+=("lists_intersect")
COMMUNITY_GENERAL_MODULE_LIST+=("lists_mergeby")
COMMUNITY_GENERAL_MODULE_LIST+=("lists_symmetric_difference")
COMMUNITY_GENERAL_MODULE_LIST+=("lists_union")
COMMUNITY_GENERAL_MODULE_LIST+=("lldp")
COMMUNITY_GENERAL_MODULE_LIST+=("locale_gen")
COMMUNITY_GENERAL_MODULE_LIST+=("lvg")
COMMUNITY_GENERAL_MODULE_LIST+=("lvg_rename")
COMMUNITY_GENERAL_MODULE_LIST+=("lvol")
COMMUNITY_GENERAL_MODULE_LIST+=("lxc_container")
COMMUNITY_GENERAL_MODULE_LIST+=("lxca_cmms")
COMMUNITY_GENERAL_MODULE_LIST+=("lxca_nodes")
COMMUNITY_GENERAL_MODULE_LIST+=("lxd_container")
COMMUNITY_GENERAL_MODULE_LIST+=("lxd_profile")
COMMUNITY_GENERAL_MODULE_LIST+=("lxd_project")
COMMUNITY_GENERAL_MODULE_LIST+=("macports")
COMMUNITY_GENERAL_MODULE_LIST+=("mail")
COMMUNITY_GENERAL_MODULE_LIST+=("make")
COMMUNITY_GENERAL_MODULE_LIST+=("maven_artifact")
COMMUNITY_GENERAL_MODULE_LIST+=("merge_variables")
COMMUNITY_GENERAL_MODULE_LIST+=("mksysb")
COMMUNITY_GENERAL_MODULE_LIST+=("modprobe")
COMMUNITY_GENERAL_MODULE_LIST+=("mssql_db")
COMMUNITY_GENERAL_MODULE_LIST+=("mssql_script")
COMMUNITY_GENERAL_MODULE_LIST+=("nagios")
COMMUNITY_GENERAL_MODULE_LIST+=("nmcli")
COMMUNITY_GENERAL_MODULE_LIST+=("npm")
COMMUNITY_GENERAL_MODULE_LIST+=("nsupdate")
COMMUNITY_GENERAL_MODULE_LIST+=("ocapi_command")
COMMUNITY_GENERAL_MODULE_LIST+=("ocapi_info")
COMMUNITY_GENERAL_MODULE_LIST+=("oci_vcn")
COMMUNITY_GENERAL_MODULE_LIST+=("odbc")
COMMUNITY_GENERAL_MODULE_LIST+=("ohai")
COMMUNITY_GENERAL_MODULE_LIST+=("open_iscsi")
COMMUNITY_GENERAL_MODULE_LIST+=("openwrt_init")
COMMUNITY_GENERAL_MODULE_LIST+=("opkg")
COMMUNITY_GENERAL_MODULE_LIST+=("osx_defaults")
COMMUNITY_GENERAL_MODULE_LIST+=("pacman")
COMMUNITY_GENERAL_MODULE_LIST+=("pacman_key")
COMMUNITY_GENERAL_MODULE_LIST+=("pam_limits")
COMMUNITY_GENERAL_MODULE_LIST+=("pamd")
COMMUNITY_GENERAL_MODULE_LIST+=("parted")
COMMUNITY_GENERAL_MODULE_LIST+=("pip_package_info")
COMMUNITY_GENERAL_MODULE_LIST+=("pipx")
COMMUNITY_GENERAL_MODULE_LIST+=("pipx_info")
COMMUNITY_GENERAL_MODULE_LIST+=("proxmox")
COMMUNITY_GENERAL_MODULE_LIST+=("proxmox_disk")
COMMUNITY_GENERAL_MODULE_LIST+=("proxmox_domain_info")
COMMUNITY_GENERAL_MODULE_LIST+=("proxmox_group_info")
COMMUNITY_GENERAL_MODULE_LIST+=("proxmox_kvm")
COMMUNITY_GENERAL_MODULE_LIST+=("proxmox_nic")
COMMUNITY_GENERAL_MODULE_LIST+=("proxmox_node_info")
COMMUNITY_GENERAL_MODULE_LIST+=("proxmox_pool")
COMMUNITY_GENERAL_MODULE_LIST+=("proxmox_pool_member")
COMMUNITY_GENERAL_MODULE_LIST+=("proxmox_snap")
COMMUNITY_GENERAL_MODULE_LIST+=("proxmox_storage_contents_info")
COMMUNITY_GENERAL_MODULE_LIST+=("proxmox_storage_info")
COMMUNITY_GENERAL_MODULE_LIST+=("proxmox_tasks_info")
COMMUNITY_GENERAL_MODULE_LIST+=("proxmox_template")
COMMUNITY_GENERAL_MODULE_LIST+=("proxmox_user_info")
COMMUNITY_GENERAL_MODULE_LIST+=("proxmox_vm_info")
COMMUNITY_GENERAL_MODULE_LIST+=("python_requirements_info")
COMMUNITY_GENERAL_MODULE_LIST+=("random_mac")
COMMUNITY_GENERAL_MODULE_LIST+=("random_pet")
COMMUNITY_GENERAL_MODULE_LIST+=("random_string")
COMMUNITY_GENERAL_MODULE_LIST+=("random_words")
COMMUNITY_GENERAL_MODULE_LIST+=("read_csv")
COMMUNITY_GENERAL_MODULE_LIST+=("redhat_subscription")
COMMUNITY_GENERAL_MODULE_LIST+=("redis")
COMMUNITY_GENERAL_MODULE_LIST+=("redis")
COMMUNITY_GENERAL_MODULE_LIST+=("redis_data")
COMMUNITY_GENERAL_MODULE_LIST+=("redis_data_incr")
COMMUNITY_GENERAL_MODULE_LIST+=("redis_data_info")
COMMUNITY_GENERAL_MODULE_LIST+=("redis_info")
COMMUNITY_GENERAL_MODULE_LIST+=("remove_keys")
COMMUNITY_GENERAL_MODULE_LIST+=("replace_keys")
COMMUNITY_GENERAL_MODULE_LIST+=("rhevm")
COMMUNITY_GENERAL_MODULE_LIST+=("rhn_channel")
COMMUNITY_GENERAL_MODULE_LIST+=("rhn_register")
COMMUNITY_GENERAL_MODULE_LIST+=("rhsm_release")
COMMUNITY_GENERAL_MODULE_LIST+=("rhsm_repository")
COMMUNITY_GENERAL_MODULE_LIST+=("sefcontext")
COMMUNITY_GENERAL_MODULE_LIST+=("selinux_permissive")
COMMUNITY_GENERAL_MODULE_LIST+=("selogin")
COMMUNITY_GENERAL_MODULE_LIST+=("seport")
COMMUNITY_GENERAL_MODULE_LIST+=("shelvefile")
COMMUNITY_GENERAL_MODULE_LIST+=("shutdown")
COMMUNITY_GENERAL_MODULE_LIST+=("snap")
COMMUNITY_GENERAL_MODULE_LIST+=("snmp_facts")
COMMUNITY_GENERAL_MODULE_LIST+=("ssh_config")
COMMUNITY_GENERAL_MODULE_LIST+=("sudoers")
COMMUNITY_GENERAL_MODULE_LIST+=("supervisorctl")
COMMUNITY_GENERAL_MODULE_LIST+=("syslogger")
COMMUNITY_GENERAL_MODULE_LIST+=("syspatch")
COMMUNITY_GENERAL_MODULE_LIST+=("sysrc")
COMMUNITY_GENERAL_MODULE_LIST+=("sysupgrade")
COMMUNITY_GENERAL_MODULE_LIST+=("terraform")
COMMUNITY_GENERAL_MODULE_LIST+=("timezone")
COMMUNITY_GENERAL_MODULE_LIST+=("to_days")
COMMUNITY_GENERAL_MODULE_LIST+=("to_hours")
COMMUNITY_GENERAL_MODULE_LIST+=("to_ini")
COMMUNITY_GENERAL_MODULE_LIST+=("to_milliseconds")
COMMUNITY_GENERAL_MODULE_LIST+=("to_minutes")
COMMUNITY_GENERAL_MODULE_LIST+=("to_months")
COMMUNITY_GENERAL_MODULE_LIST+=("to_seconds")
COMMUNITY_GENERAL_MODULE_LIST+=("to_time_unit")
COMMUNITY_GENERAL_MODULE_LIST+=("to_weeks")
COMMUNITY_GENERAL_MODULE_LIST+=("to_years")
COMMUNITY_GENERAL_MODULE_LIST+=("ufw")
COMMUNITY_GENERAL_MODULE_LIST+=("unicode_normalize")
COMMUNITY_GENERAL_MODULE_LIST+=("uptimerobot")
COMMUNITY_GENERAL_MODULE_LIST+=("usb_facts")
COMMUNITY_GENERAL_MODULE_LIST+=("version_sort")
COMMUNITY_GENERAL_MODULE_LIST+=("vmadm")
COMMUNITY_GENERAL_MODULE_LIST+=("wakeonlan")
COMMUNITY_GENERAL_MODULE_LIST+=("xattr")
COMMUNITY_GENERAL_MODULE_LIST+=("xenserver_facts")
COMMUNITY_GENERAL_MODULE_LIST+=("xenserver_guest")
COMMUNITY_GENERAL_MODULE_LIST+=("xenserver_guest_info")
COMMUNITY_GENERAL_MODULE_LIST+=("xenserver_guest_powerstate")
COMMUNITY_GENERAL_MODULE_LIST+=("xfconf")
COMMUNITY_GENERAL_MODULE_LIST+=("xfconf_info")
COMMUNITY_GENERAL_MODULE_LIST+=("xfs_quota")
COMMUNITY_GENERAL_MODULE_LIST+=("xml")
COMMUNITY_GENERAL_MODULE_LIST+=("yarn")
COMMUNITY_GENERAL_MODULE_LIST+=("yum_versionlock")
COMMUNITY_GENERAL_MODULE_LIST+=("zfs")
COMMUNITY_GENERAL_MODULE_LIST+=("zfs_delegate_admin")
COMMUNITY_GENERAL_MODULE_LIST+=("zfs_facts")
COMMUNITY_GENERAL_MODULE_LIST+=("znode")
COMMUNITY_GENERAL_MODULE_LIST+=("zpool_facts")
COMMUNITY_GENERAL_MODULE_LIST+=("zypper")
COMMUNITY_GENERAL_MODULE_LIST+=("zypper_repository")

#COMMUNITY_GENERAL_MODULES_REGEX=" (alternatives|ansible_galaxy_install|apache2_mod_proxy|apache2_module|apk|apt_repo|apt_rpm|archive|btrfs_info|btrfs_subvolume|bundler|bzr|capabilities|cargo|cartesian|cloud_init_data_facts|cloudflare_dns|collection_version|consul_kv|counter|cpanm|crc32|cronvar|crypttab|cyberarkpassword|dependent|dict|dict_kv|dig|dnf_config_manager|dnf_versionlock|dnsimple|dnsimple_info|dnsmadeeasy|dnstxt|dpkg_divert|dsv|easy_install|etcd|etcd3|etcd3|facter|facter_facts|filesize|filesystem|filetree|flattened|from_csv|from_ini|git_config|git_config_info|groupby_as_dict|gunicorn|haproxy|hashids_decode|hashids_encode|homebrew|homebrew_cask|homebrew_tap|homectl|htpasswd|ini_file|interfaces_file|ip_netns|ipbase_info|ipify_facts|ipinfoio_facts|ipmi_boot|ipmi_power|iptables_state|iso_create|iso_customize|iso_extract|java_cert|java_keystore|jboss|jc|jenkins_build|jenkins_build_info|jenkins_job|jenkins_job_info|jenkins_plugin|jenkins_script|json_query|keep_keys|kernel_blacklist|keyring|keyring|keyring_info|launchd|ldap_attrs|ldap_entry|ldap_passwd|ldap_search|listen_ports_facts|lists_difference|lists_intersect|lists_mergeby|lists_symmetric_difference|lists_union|lldp|locale_gen|lvg|lvg_rename|lvol|lxc_container|lxca_cmms|lxca_nodes|lxd_container|lxd_profile|lxd_project|macports|mail|make|maven_artifact|merge_variables|mksysb|modprobe|mssql_db|mssql_script|nagios|nmcli|npm|nsupdate|ocapi_command|ocapi_info|oci_vcn|odbc|ohai|open_iscsi|openwrt_init|opkg|osx_defaults|pacman|pacman_key|pam_limits|pamd|parted|pip_package_info|pipx|pipx_info|proxmox|proxmox_disk|proxmox_domain_info|proxmox_group_info|proxmox_kvm|proxmox_nic|proxmox_node_info|proxmox_pool|proxmox_pool_member|proxmox_snap|proxmox_storage_contents_info|proxmox_storage_info|proxmox_tasks_info|proxmox_template|proxmox_user_info|proxmox_vm_info|python_requirements_info|random_mac|random_pet|random_string|random_words|read_csv|redhat_subscription|redis|redis|redis_data|redis_data_incr|redis_data_info|redis_info|remove_keys|replace_keys|rhevm|rhn_channel|rhn_register|rhsm_release|rhsm_repository|sefcontext|selinux_permissive|selogin|seport|shelvefile|shutdown|snap|snmp_facts|ssh_config|sudoers|supervisorctl|syslogger|syspatch|sysrc|sysupgrade|terraform|timezone|to_days|to_hours|to_ini|to_milliseconds|to_minutes|to_months|to_seconds|to_time_unit|to_weeks|to_years|ufw|unicode_normalize|uptimerobot|usb_facts|version_sort|vmadm|wakeonlan|xattr|xenserver_facts|xenserver_guest|xenserver_guest_info|xenserver_guest_powerstate|xfconf|xfconf_info|xfs_quota|xml|yarn|yum_versionlock|zfs|zfs_delegate_admin|zfs_facts|znode|zpool_facts|zypper|zypper_repository):\s*$"
# to community.general.$1



COMMUNITY_WINDOWS_MODULE_LIST=()
COMMUNITY_WINDOWS_MODULE_LIST+=("psexec")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_audit_policy_system")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_audit_rule")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_auto_logon")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_certificate_info")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_computer_description")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_credential")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_data_deduplication")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_defrag")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_dhcp_lease")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_disk_facts")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_disk_image")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_dns_record")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_dns_zone")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_domain_computer")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_domain_group")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_domain_group_membership")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_domain_object_info")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_domain_ou")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_domain_user")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_dotnet_ngen")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_eventlog")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_eventlog_entry")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_feature_info")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_file_compression")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_file_version")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_firewall")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_firewall_rule")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_format")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_hosts")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_hotfix")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_http_proxy")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_iis_virtualdirectory")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_iis_webapplication")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_iis_webapppool")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_iis_webbinding")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_iis_website")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_inet_proxy")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_initialize_disk")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_lineinfile")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_listen_ports_facts")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_mapped_drive")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_msg")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_net_adapter_feature")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_netbios")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_nssm")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_pagefile")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_partition")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_pester")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_power_plan")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_product_facts")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_psexec")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_psmodule")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_psmodule_info")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_psrepository")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_psrepository_copy")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_psrepository_info")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_psscript")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_psscript_info")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_pssession_configuration")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_rabbitmq_plugin")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_rds_cap")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_rds_rap")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_rds_settings")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_region")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_regmerge")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_robocopy")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_route")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_say")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_scheduled_task")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_scheduled_task_stat")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_scoop")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_scoop_bucket")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_security_policy")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_shortcut")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_snmp")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_timezone")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_toast")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_unzip")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_user_profile")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_wait_for_process")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_wakeonlan")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_webpicmd")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_xml")
COMMUNITY_WINDOWS_MODULE_LIST+=("win_zip")

#COMMUNITY_WINDOWS_MODULES_REGEX=" (psexec|win_audit_policy_system|win_audit_rule|win_auto_logon|win_certificate_info|win_computer_description|win_credential|win_data_deduplication|win_defrag|win_dhcp_lease|win_disk_facts|win_disk_image|win_dns_record|win_dns_zone|win_domain_computer|win_domain_group|win_domain_group_membership|win_domain_object_info|win_domain_ou|win_domain_user|win_dotnet_ngen|win_eventlog|win_eventlog_entry|win_feature_info|win_file_compression|win_file_version|win_firewall|win_firewall_rule|win_format|win_hosts|win_hotfix|win_http_proxy|win_iis_virtualdirectory|win_iis_webapplication|win_iis_webapppool|win_iis_webbinding|win_iis_website|win_inet_proxy|win_initialize_disk|win_lineinfile|win_listen_ports_facts|win_mapped_drive|win_msg|win_net_adapter_feature|win_netbios|win_nssm|win_pagefile|win_partition|win_pester|win_power_plan|win_product_facts|win_psexec|win_psmodule|win_psmodule_info|win_psrepository|win_psrepository_copy|win_psrepository_info|win_psscript|win_psscript_info|win_pssession_configuration|win_rabbitmq_plugin|win_rds_cap|win_rds_rap|win_rds_settings|win_region|win_regmerge|win_robocopy|win_route|win_say|win_scheduled_task|win_scheduled_task_stat|win_scoop|win_scoop_bucket|win_security_policy|win_shortcut|win_snmp|win_timezone|win_toast|win_unzip|win_user_profile|win_wait_for_process|win_wakeonlan|win_webpicmd|win_xml|win_zip):"
# to community.windows.win_psmodule


COMMUNITY_DOCKER_MODULE_LIST=()
COMMUNITY_DOCKER_MODULE_LIST+=("current_container_facts")
COMMUNITY_DOCKER_MODULE_LIST+=("docker_compose")
COMMUNITY_DOCKER_MODULE_LIST+=("docker_compose_v2")
COMMUNITY_DOCKER_MODULE_LIST+=("docker_compose_v2_pull")
COMMUNITY_DOCKER_MODULE_LIST+=("docker_config")
COMMUNITY_DOCKER_MODULE_LIST+=("docker_container")
COMMUNITY_DOCKER_MODULE_LIST+=("docker_container_copy_into")
COMMUNITY_DOCKER_MODULE_LIST+=("docker_container_exec")
COMMUNITY_DOCKER_MODULE_LIST+=("docker_container_info")
COMMUNITY_DOCKER_MODULE_LIST+=("docker_host_info")
COMMUNITY_DOCKER_MODULE_LIST+=("docker_image")
COMMUNITY_DOCKER_MODULE_LIST+=("docker_image_build")
COMMUNITY_DOCKER_MODULE_LIST+=("docker_image_export")
COMMUNITY_DOCKER_MODULE_LIST+=("docker_image_info")
COMMUNITY_DOCKER_MODULE_LIST+=("docker_image_load")
COMMUNITY_DOCKER_MODULE_LIST+=("docker_image_pull")
COMMUNITY_DOCKER_MODULE_LIST+=("docker_image_push")
COMMUNITY_DOCKER_MODULE_LIST+=("docker_image_remove")
COMMUNITY_DOCKER_MODULE_LIST+=("docker_image_tag")
COMMUNITY_DOCKER_MODULE_LIST+=("docker_login")
COMMUNITY_DOCKER_MODULE_LIST+=("docker_network")
COMMUNITY_DOCKER_MODULE_LIST+=("docker_network_info")
COMMUNITY_DOCKER_MODULE_LIST+=("docker_node")
COMMUNITY_DOCKER_MODULE_LIST+=("docker_node_info")
COMMUNITY_DOCKER_MODULE_LIST+=("docker_plugin")
COMMUNITY_DOCKER_MODULE_LIST+=("docker_prune")
COMMUNITY_DOCKER_MODULE_LIST+=("docker_secret")
COMMUNITY_DOCKER_MODULE_LIST+=("docker_stack")
COMMUNITY_DOCKER_MODULE_LIST+=("docker_stack_info")
COMMUNITY_DOCKER_MODULE_LIST+=("docker_stack_task_info")
COMMUNITY_DOCKER_MODULE_LIST+=("docker_swarm")
COMMUNITY_DOCKER_MODULE_LIST+=("docker_swarm_info")
COMMUNITY_DOCKER_MODULE_LIST+=("docker_swarm_service")
COMMUNITY_DOCKER_MODULE_LIST+=("docker_swarm_service_info")
COMMUNITY_DOCKER_MODULE_LIST+=("docker_volume")
COMMUNITY_DOCKER_MODULE_LIST+=("docker_volume_info")

#COMMUNITY_DOCKER_MODULES_REGEX=" (current_container_facts|docker_compose|docker_compose_v2|docker_compose_v2_pull|docker_config|docker_container|docker_container_copy_into|docker_container_exec|docker_container_info|docker_host_info|docker_image|docker_image_build|docker_image_export|docker_image_info|docker_image_load|docker_image_pull|docker_image_push|docker_image_remove|docker_image_tag|docker_login|docker_network|docker_network_info|docker_node|docker_node_info|docker_plugin|docker_prune|docker_secret|docker_stack|docker_stack_info|docker_stack_task_info|docker_swarm|docker_swarm_info|docker_swarm_service|docker_swarm_service_info|docker_volume|docker_volume_info):\s*$"
# to community.docker.$1

OPENSTACK_CLOUD_MODULE_LIST=()
OPENSTACK_CLOUD_MODULE_LIST+=("current_container_facts")


OPENSTACK_CLOUD_MODULE_LIST+=("address_scope")
OPENSTACK_CLOUD_MODULE_LIST+=("auth")
OPENSTACK_CLOUD_MODULE_LIST+=("baremetal_deploy_template")
OPENSTACK_CLOUD_MODULE_LIST+=("baremetal_inspect")
OPENSTACK_CLOUD_MODULE_LIST+=("baremetal_node")
OPENSTACK_CLOUD_MODULE_LIST+=("baremetal_node_action")
OPENSTACK_CLOUD_MODULE_LIST+=("baremetal_node_info")
OPENSTACK_CLOUD_MODULE_LIST+=("baremetal_port")
OPENSTACK_CLOUD_MODULE_LIST+=("baremetal_port_info")
OPENSTACK_CLOUD_MODULE_LIST+=("catalog_service")
OPENSTACK_CLOUD_MODULE_LIST+=("catalog_service_info")
OPENSTACK_CLOUD_MODULE_LIST+=("coe_cluster")
OPENSTACK_CLOUD_MODULE_LIST+=("coe_cluster_template")
OPENSTACK_CLOUD_MODULE_LIST+=("compute_flavor")
OPENSTACK_CLOUD_MODULE_LIST+=("compute_flavor_access")
OPENSTACK_CLOUD_MODULE_LIST+=("compute_flavor_info")
OPENSTACK_CLOUD_MODULE_LIST+=("compute_service_info")
OPENSTACK_CLOUD_MODULE_LIST+=("config")
OPENSTACK_CLOUD_MODULE_LIST+=("dns_zone")
OPENSTACK_CLOUD_MODULE_LIST+=("dns_zone_info")
OPENSTACK_CLOUD_MODULE_LIST+=("endpoint")
OPENSTACK_CLOUD_MODULE_LIST+=("federation_idp")
OPENSTACK_CLOUD_MODULE_LIST+=("federation_idp_info")
OPENSTACK_CLOUD_MODULE_LIST+=("federation_mapping")
OPENSTACK_CLOUD_MODULE_LIST+=("federation_mapping_info")
OPENSTACK_CLOUD_MODULE_LIST+=("floating_ip")
OPENSTACK_CLOUD_MODULE_LIST+=("floating_ip_info")
OPENSTACK_CLOUD_MODULE_LIST+=("group_assignment")
OPENSTACK_CLOUD_MODULE_LIST+=("host_aggregate")
OPENSTACK_CLOUD_MODULE_LIST+=("identity_domain")
OPENSTACK_CLOUD_MODULE_LIST+=("identity_domain_info")
OPENSTACK_CLOUD_MODULE_LIST+=("identity_group")
OPENSTACK_CLOUD_MODULE_LIST+=("identity_group_info")
OPENSTACK_CLOUD_MODULE_LIST+=("identity_role")
OPENSTACK_CLOUD_MODULE_LIST+=("identity_role_info")
OPENSTACK_CLOUD_MODULE_LIST+=("identity_user")
OPENSTACK_CLOUD_MODULE_LIST+=("identity_user_info")
OPENSTACK_CLOUD_MODULE_LIST+=("image")
OPENSTACK_CLOUD_MODULE_LIST+=("image_info")
OPENSTACK_CLOUD_MODULE_LIST+=("keypair")
OPENSTACK_CLOUD_MODULE_LIST+=("keypair_info")
OPENSTACK_CLOUD_MODULE_LIST+=("keystone_federation_protocol")
OPENSTACK_CLOUD_MODULE_LIST+=("keystone_federation_protocol_info")
OPENSTACK_CLOUD_MODULE_LIST+=("lb_health_monitor")
OPENSTACK_CLOUD_MODULE_LIST+=("lb_listener")
OPENSTACK_CLOUD_MODULE_LIST+=("lb_member")
OPENSTACK_CLOUD_MODULE_LIST+=("lb_pool")
OPENSTACK_CLOUD_MODULE_LIST+=("loadbalancer")
OPENSTACK_CLOUD_MODULE_LIST+=("network")
OPENSTACK_CLOUD_MODULE_LIST+=("networks_info")
OPENSTACK_CLOUD_MODULE_LIST+=("neutron_rbac_policies_info")
OPENSTACK_CLOUD_MODULE_LIST+=("neutron_rbac_policy")
OPENSTACK_CLOUD_MODULE_LIST+=("object")
OPENSTACK_CLOUD_MODULE_LIST+=("object_container")
OPENSTACK_CLOUD_MODULE_LIST+=("port")
OPENSTACK_CLOUD_MODULE_LIST+=("port_info")
OPENSTACK_CLOUD_MODULE_LIST+=("project")
OPENSTACK_CLOUD_MODULE_LIST+=("project_info")
OPENSTACK_CLOUD_MODULE_LIST+=("quota")
OPENSTACK_CLOUD_MODULE_LIST+=("recordset")
OPENSTACK_CLOUD_MODULE_LIST+=("resource")
OPENSTACK_CLOUD_MODULE_LIST+=("resources")
OPENSTACK_CLOUD_MODULE_LIST+=("role_assignment")
OPENSTACK_CLOUD_MODULE_LIST+=("router")
OPENSTACK_CLOUD_MODULE_LIST+=("routers_info")
OPENSTACK_CLOUD_MODULE_LIST+=("security_group")
OPENSTACK_CLOUD_MODULE_LIST+=("security_group_info")
OPENSTACK_CLOUD_MODULE_LIST+=("security_group_rule")
OPENSTACK_CLOUD_MODULE_LIST+=("security_group_rule_info")
OPENSTACK_CLOUD_MODULE_LIST+=("server")
OPENSTACK_CLOUD_MODULE_LIST+=("server_action")
OPENSTACK_CLOUD_MODULE_LIST+=("server_group")
OPENSTACK_CLOUD_MODULE_LIST+=("server_info")
OPENSTACK_CLOUD_MODULE_LIST+=("server_metadata")
OPENSTACK_CLOUD_MODULE_LIST+=("server_volume")
OPENSTACK_CLOUD_MODULE_LIST+=("stack")
OPENSTACK_CLOUD_MODULE_LIST+=("stack_info")
OPENSTACK_CLOUD_MODULE_LIST+=("subnet")
OPENSTACK_CLOUD_MODULE_LIST+=("subnet_pool")
OPENSTACK_CLOUD_MODULE_LIST+=("subnets_info")
OPENSTACK_CLOUD_MODULE_LIST+=("volume")
OPENSTACK_CLOUD_MODULE_LIST+=("volume_backup")
OPENSTACK_CLOUD_MODULE_LIST+=("volume_backup_info")
OPENSTACK_CLOUD_MODULE_LIST+=("volume_info")
OPENSTACK_CLOUD_MODULE_LIST+=("volume_snapshot")
OPENSTACK_CLOUD_MODULE_LIST+=("volume_snapshot_info")
OPENSTACK_CLOUD_MODULE_LIST+=("volume_type")
OPENSTACK_CLOUD_MODULE_LIST+=("volume_type_access")
OPENSTACK_CLOUD_MODULE_LIST+=("volume_type_encryption")
OPENSTACK_CLOUD_MODULE_LIST+=("volume_type_info")


#OPENSTACK_CLOUD_MODULES_REGEX=" (address_scope|auth|baremetal_deploy_template|baremetal_inspect|baremetal_node|baremetal_node_action|baremetal_node_info|baremetal_port|baremetal_port_info|catalog_service|catalog_service_info|coe_cluster|coe_cluster_template|compute_flavor|compute_flavor_access|compute_flavor_info|compute_service_info|config|dns_zone|dns_zone_info|endpoint|federation_idp|federation_idp_info|federation_mapping|federation_mapping_info|floating_ip|floating_ip_info|group_assignment|host_aggregate|identity_domain|identity_domain_info|identity_group|identity_group_info|identity_role|identity_role_info|identity_user|identity_user_info|image|image_info|keypair|keypair_info|keystone_federation_protocol|keystone_federation_protocol_info|lb_health_monitor|lb_listener|lb_member|lb_pool|loadbalancer|network|networks_info|neutron_rbac_policies_info|neutron_rbac_policy|object|object_container|port|port_info|project|project_info|quota|recordset|resource|resources|role_assignment|router|routers_info|security_group|security_group_info|security_group_rule|security_group_rule_info|server|server_action|server_group|server_info|server_metadata|server_volume|stack|stack_info|subnet|subnet_pool|subnets_info|volume|volume_backup|volume_backup_info|volume_info|volume_snapshot|volume_snapshot_info|volume_type|volume_type_access|volume_type_encryption|volume_type_info):\s*$"
# to openstack.cloud.$1



## ref: https://stackoverflow.com/questions/4569825/sed-one-liner-to-convert-all-uppercase-to-lowercase
echo "Convert first lowercase letter of tasks name to upper case to pass linting tests"
sed -i '/\- name\: \"([a-z])/\- name\: \"\U$1/' tasks/*.yml


Add name for debug execs:
```shell
## from
^([ ]*)\- ansible.builtin.(include_tasks|import_tasks): (.*)$

## to
$1- name: Run $3
$1  ansible\.builtin\.$2\: $3

```

Add name for debug execs:
```shell
## from
^([ ]*)\- ansible\.builtin\.debug\:$
^([ ]*)var\: (.*)$

## to
$1- name: Display $3
$1  ansible\.builtin\.debug\:
$1    var\: $3

```


Add name for debug msg execs:
```shell
## from
^([ ]*)\- ansible\.builtin\.debug\:$
^([ ]*)msg\:$

## to
$1- name: Display info
$1  ansible\.builtin\.debug\:
$1    msg\:

```

Add name for set_fact execs:
```shell
## from
^([ ]*)\- ansible\.builtin\.set_fact\:$
^([ ]*)(.*)\: (.*)$

## to
$1- name: Set $3
$1  ansible\.builtin\.set_fact\:
$1    $3\: $4

```

