#!/usr/bin/env bash

TARGET_HOST=${1:-media.johnson.int}
TARGET_PORT=${2:-5000}
#CONTEXT_PATH=${3:-"v2/"}
CONTEXT_PATH=${3:-"v2/_catalog"}

DOCKER_REGISTRY_USERNAME=${DOCKER_REGISTRY_USERNAME:-""}
DOCKER_REGISTRY_PASSWORD=${DOCKER_REGISTRY_PASSWORD:-""}

CREDS=${DOCKER_REGISTRY_USERNAME}:${DOCKER_REGISTRY_PASSWORD}

SCRIPT_DIR="$( cd "$( dirname "$0" )" && pwd )"
echo "SCRIPT_DIR=${SCRIPT_DIR}"

#${SCRIPT_DIR}/validate-ssl-endpoint.sh -c ${CREDS} -p ${CONTEXT_PATH} ${TARGET_HOST} ${TARGET_PORT}
VALIDATE_CMD="${SCRIPT_DIR}/validate-ssl-endpoint.sh"

if [[ "${CREDENTIALS}" != "" ]]; then
  VALIDATE_CMD+=" -c ${CREDS}"
fi
VALIDATE_CMD+=" -p ${CONTEXT_PATH} ${TARGET_HOST} ${TARGET_PORT}"
echo "${VALIDATE_CMD}"
${VALIDATE_CMD}
